# See https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false