name: "Ruby Testing"
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
        
      - name: Install system dependencies
        run: |
          sudo apt install libpq-dev
          gem install bundler

      - name: Install gems
        run: bundle install

      - name: Set up database schema
        run: bin/rails db:create db:schema:load

      - name: Run tests
        run: bundle exec rspec
